# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expmAtv_cpp <- function(evecs, evals, v, d, dInv, t = 300, preMultiply = FALSE) {
    .Call(`_dsdive_expmAtv_cpp`, evecs, evals, v, d, dInv, t, preMultiply)
}

expm_cpp <- function(A, delta = 1e-15, t = 300, tol = 1e-15) {
    .Call(`_dsdive_expm_cpp`, A, delta, t, tol)
}

